uploads = []
generated = []

[[outputs]]
id = "zplh5MDxKJzfQXcoeletb"
uri = "file://julian-motors-project.zip"
type = "unspecified"
title = "Julian Motors — полный проект"

[[outputs]]
id = "yKpN2TZ63ltI-zFvvnKiW"
uri = "file://julianmotors-latest.zip"
type = "unspecified"
title = "Julian Motors — полный проект (актуальная версия)"

[[outputs]]
id = "qsW_y4OJBVlZ09uXBdRhK"
uri = "file://julianmotors-hostinger.zip"
type = "unspecified"
title = "Julian Motors — ZIP для Hostinger"

[[outputs]]
id = "4hHhVliBShYWANCWfJvyb"
uri = "file://julianmotors-site.zip"
type = "unspecified"
title = "Julian Motors — сайт для хостинга"
